TECH/907
godspeedsystems/godspeed-scaffolding pull request #13
Opened 2024-01-11 12:46 UTC by xCodeMuse

PENDING
- [ ] ](https://github.com/godspeedsystems/gs-node-service/issues/907)

2024-01-18 20:10 UTC, mastersilv3r requested changes

2024-01-18 20:10 UTC, mastersilv3r commented on .template/dot-configs/.env
Please remove admin and mindgrep from here. use <user>:<password>

2024-01-18 20:10 UTC, mastersilv3r commented on .template/dot-configs/.eslintrc.json
> +    "no-unused-vars": "off",
on

2024-01-18 20:10 UTC, mastersilv3r commented on .template/dot-configs/.eslintrc.json
> +    "@typescript-eslint/no-unused-vars": 0,
on

2024-01-18 20:10 UTC, mastersilv3r commented on .template/package.json
> +    "build": "swc src -d dist && rsync -a --exclude '*.ts' ./src/ ./dist/ && rsync -a ./config/ ./dist/config && rsync -a ./src/mappings/ ./dist/mappings && rsync -a ./src/plugins/ ./dist/plugins &&
Remove transpiler command for now.

2024-01-21 07:09 UTC, kushal-godspeed approved these changes

2024-01-21 07:11 UTC, merged